# 股票消息爬虫系统配置文件

# 数据库配置
database:
  host: 172.16.205.22
  port: 9301
  user: root
  password: "root@123"  # 请填入您的MySQL密码
  database: stock_message

# 爬虫配置
spider:
  interval: 60  # 爬虫运行间隔（秒）
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  max_retry_times: 3  # 最大重试次数
  request_timeout: 30  # 请求超时时间（秒）

# 图片缓存配置
image_cache:
  enabled: true  # 是否启用图片缓存
  cache_dir: "static/images/cache"  # 缓存目录
  expire_hours: 24  # 缓存有效期（小时）
  max_size_mb: 500  # 最大缓存大小（MB）
  allowed_formats: ["jpg", "jpeg", "png", "gif", "webp"]  # 允许的图片格式
  max_file_size_mb: 10  # 单个文件最大大小（MB）

# 日志配置
logging:
  level: INFO  # 日志级别：DEBUG, INFO, WARNING, ERROR
  file: logs/stock_message.log  # 日志文件路径